---

- name: Install Odoo dependencies
  apt:  pkg={{ item }}
        state=installed
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}
  with_items: "{{ odoo_debian_packages }}"
  tags:
    - odoo_packages

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"
  tags:
    - odoo_packages

- include: config.yml
  tags:
    - odoo_config

- name: Generate Odoo init script
  template: src=odoo-{{ odoo_version }}.init dest=/etc/init.d/{{ odoo_service }}
        owner=root group=root mode=0755
        force={{ odoo_force_config and 'yes' or 'no' }}
        backup=yes
  notify: Restart Odoo
