---

- name: Install required tools
  apt:  pkg={{ item }}
        state=installed
        update_cache=yes
  with_items: "{{ odoo_required_tools }}"
  tags:
    - odoo_required_tools

- name: Install Odoo dependencies
  apt:  pkg={{ item }}
        state=installed
        update_cache=yes
  with_items: "{{ odoo_debian_packages }}"
  tags:
    - odoo_packages

- name: Install Odoo dependencies (PyPi)
  pip: name={{ item }}
  with_items: "{{ odoo_pypi_packages }}"
  tags:
    - odoo_packages

- name: Install Odoo dependencies (npm)
  include: install_npm.yml
  when: (odoo_version | int) >= 9
  tags:
    - odoo
    - odoo_packages

- name: Add Odoo system user
  user: name={{ odoo_user }} shell=/bin/bash
        password={{ odoo_user_passwd }} update_password=on_create
        system={{ odoo_user_system }}
  tags:
    - odoo_user

- name: Create log directory
  file: path={{ odoo_logdir }} state=directory
        owner={{ odoo_user }} group={{ odoo_user }} force=no
  tags:
    - odoo_log

- name: Project repository already cloned?
  stat: path={{ odoo_repo_dest }}
  register: project_path
  tags:
    - odoo_project

- name: Clone project repository (Mercurial)
  become: yes
  become_user: "{{ odoo_user }}"
  hg:   repo={{ odoo_repo_url }}
        dest={{ odoo_repo_dest }}
        revision={{ odoo_repo_rev | string }}
  when: odoo_repo_type == 'hg' and odoo_repo_url
        and (odoo_repo_update or (project_path.stat.exists == False))
  notify: Restart Odoo
  tags:
    - odoo_project

- name: Clone project repository (Git)
  become: yes
  become_user: "{{ odoo_user }}"
  git:  repo={{ odoo_repo_url }}
        dest={{ odoo_repo_dest }}
        version={{ odoo_repo_rev | string }}
        update={{ project_path.stat.exists == False and 'yes'
                  or (odoo_repo_update and 'yes' or 'no') }}
        depth={{ odoo_repo_depth }}
  when: odoo_repo_type == 'git' and odoo_repo_url
  notify: Restart Odoo
  tags:
    - odoo_project
