---

- name: Install npm
  apt:  pkg=npm
        state=installed
        update_cache={{ odoo_apt_update_cache }}
        cache_valid_time={{ odoo_apt_cache_valid_time }}

- name: Check that '/usr/bin/nodejs' exists
  stat: path=/usr/bin/nodejs
  register: nodejs_executable

- name: Check that '/usr/local/bin/node' exists
  stat: path=/usr/local/bin/node
  register: node_executable

- name: Add symlink '/usr/local/bin/node'
  file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link
  when: nodejs_executable.stat.exists and node_executable.stat.exists == False

- name: Install Odoo dependencies (npm)
  npm:  name={{ item.name }}
        version={{ item.version }}
        global=yes
  with_items: "{{ odoo_npm_packages | default([]) }}"
