---

- name: Read SSH Keys
  local_action:
    shell cat {{ odoo_user_sshkeys }}
  register: all_ssh_keys

- name: Set SSH public keys for the Odoo user
  authorized_key: user={{ odoo_user }}
                  key="{{ all_ssh_keys.stdout }}"
  when: all_ssh_keys.stdout
