---

- include: install.yml
  tags:
    - odoo
    - odoo_install

- include: config.yml
  tags:
    - odoo
    - odoo_config

- include: postgresql.yml
  tags:
    - odoo
    - odoo_postgresql

- include: service.yml
  tags:
    - odoo
    - odoo_service
