---

- name: check "{{ lxd_container_name }}" if exist
  shell: "lxc list |grep ' {{ lxd_container_name }} ' |cut -d'|' -f6 | awk '{print $1}'"
  register: lxd_state
  when: lxd_type == True

- debug:
    msg: The {{ lxd_container_name }} container is exist
  when: lxd_type == True and lxd_state.stdout == "PERSISTENT"

- meta: end_play
  when: new_lxd_container == True and lxd_type == True and lxd_state.stdout == "PERSISTENT"

- name: Be careful
  debug:
    msg:
      -      Warning           Warning           Warning            Warning
      - You chose 'new_lxd_container == False', That mean ansible will overwrite the exist container.
      - If you are sure press 'c then Enter' to containeu.
      - If you make it by mistake press 'q then Enter' then correct new_lxd_container variable to be 'True' and chose other lxd_container_name, then rerun ansible-playbook.
  failed_when: True
  ignore_errors: True
  when: new_lxd_container == False and lxd_type == True and lxd_state.stdout == "PERSISTENT"

- name: create "{{ lxd_container_name }}"
  import_tasks: create_lxd_container.yml
  when: lxd_type == True and lxd_container_name != "localhost" and lxd_step == True



- name: Work into LXD container
  delegate_to: "{{ lxd_container_name }}"
  import_tasks: work_into_lxd_container.yml
  tags:
    - lxd_container
  when: lxd_type

- name: Create and config LXD postgresql database
  import_tasks: lxd_postgresql.yml
  when: lxd_type == False and postgresql_step == True

- name: Direct intallation
  import_tasks: direct_installation.yml
  tags:
    - direct_installation
  when: lxd_type == False

- name: Config LXD container in nginx
  import_tasks: config_nginx_proxy.yml
  tags:
    - nginx
    - lxd_container
    - lxd
  when: nginx_step

- debug:
    msg:
      - For more information please read our toturial
      - https://github.com/sunflowerit/ansible-odoo
