---

- name: Setting variables depending on the Odoo version
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/Odoo-{{ odoo_version | int }}.yml"
  tags:
    - always

- name: Setting variables depending on the distribution release
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
  tags:
    - always

- include: install.yml
  tags:
    - odoo
    - odoo_install

- include: wkhtmltox.yml
  tags:
    - odoo
    - odoo_wkhtmltox

- include: reportlab.yml
  tags:
    - odoo
    - odoo_reportlab

- include: postgresql.yml
  tags:
    - odoo
    - odoo_postgresql

- include: service.yml
  tags:
    - odoo
    - odoo_service
