---

- name: Setting variables depending on the Odoo version
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/Odoo-{{ odoo_version | int }}.yml"
  tags:
    - always

- name: Setting variables depending on the distribution release
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
  tags:
    - always

- include: install.yml
  tags:
    - odoo
    - odoo_install

- include: install_extra.yml
  when: odoo_user_sshkeys is defined and odoo_user_sshkeys
  tags:
    - odoo
    - odoo_install
    - odoo_install_extra

- include: wkhtmltox.yml
  tags:
    - odoo
    - odoo_wkhtmltox

- include: reportlab.yml
  tags:
    - odoo
    - odoo_reportlab

- include: config.yml
  tags:
    - odoo
    - odoo_config

- include: postgresql_local.yml
  when: odoo_config_db_host in [False, 'localhost', '127.0.0.1']
  tags:
    - odoo
    - odoo_postgresql
    - odoo_postgresql_local

- include: postgresql_remote.yml
  when: odoo_config_db_host not in [False, 'localhost', '127.0.0.1']
  tags:
    - odoo
    - odoo_postgresql
    - odoo_postgresql_remote

- include: service.yml
  tags:
    - odoo
    - odoo_service
