- name: Remote PostgreSQL - Add the Odoo user
  delegate_to: "{{ odoo_config_db_host }}"
  remote_user: "{{ odoo_config_db_host_user }}"
  become: yes
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                   role_attr_flags={{ odoo_postgresql_user_role_attr }}
  when: odoo_postgresql_set_user

- name: Remote PostgreSQL - Set the Odoo user password
  delegate_to: "{{ odoo_config_db_host }}"
  remote_user: "{{ odoo_config_db_host_user }}"
  become: yes
  become_user: postgres
  postgresql_user: name={{ odoo_config_db_user }}
                   password={{ odoo_config_db_passwd }}
  when: odoo_config_db_passwd is defined and odoo_config_db_passwd
        and odoo_postgresql_set_user

- name: Remote PostgreSQL - Active the 'unaccent' extension on databases
  delegate_to: "{{ odoo_config_db_host }}"
  remote_user: "{{ odoo_config_db_host_user }}"
  become: yes
  become_user: postgres
  postgresql_ext: name=unaccent db=template1
  when: odoo_config_unaccent
        and odoo_postgresql_active_unaccent
