---
# Download and install the barcode fonts from ReportLab
- name: Download the ReportLab barcode fonts
  get_url: url="{{ odoo_reportlab_font_url }}"
           dest="/opt/pfbfer.zip"

- name: Create the font directory
  file: path="{{ odoo_workdir }}/fonts" state=directory

- name: Install unzip
  apt: name=unzip state=present

- name: Unzip the ReportLab fonts
  unarchive: src="/opt/pfbfer.zip"
             dest="{{ odoo_workdir }}/fonts"
             owner={{ odoo_user }}
             group={{ odoo_user }}
             mode="u=rwX,go=rX"
             copy=No
             creates="{{ odoo_workdir }}/fonts/_abi____.pfb"
